Repository CSC59939/LunchIn, pull requests merged in 2018-12, with the labels that each got.

#72 Chc refactor userinputfoodchoices
  client/src/BusinessCardList/BusinessCard.test.js
  client/src/BusinessCardList/BusinessCardList.js
  client/src/BusinessCardList/ReviewList/Review.js
  client/src/BusinessCardList/__snapshots__/BusinessCard.test.js.snap
  client/src/BusinessCardList/__snapshots__/BusinessCardList.test.js.snap
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
  client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
Labels: Feature/Enhancement

#82 Gerry material ui deprecation fix
  client/src/Home/Home.js
  client/src/Home/Signup/Signup.js
  client/src/Home/Signup/__snapshots__/Signup.test.js.snap
  client/src/Home/__snapshots__/Home.test.js.snap
  client/src/User/UserHome/UserHome.js
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
  client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
  client/src/User/UserHome/UserProfile/UserProfile.js
  client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
  client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
  client/src/index.js
Labels: Feature/Enhancement

#84 Chc yelp round robin
  server/.gitignore
  server/controllers/yelpApi.js
Labels: Feature/Enhancement

#83 Luis zipcode (new page)
  client/src/User/UserHome/UserHome.js
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
  client/src/User/UserHome/Zipcode/Zipcode.css
  client/src/User/UserHome/Zipcode/Zipcode.js
  client/src/User/UserHome/Zipcode/Zipcode.test.js
  client/src/User/UserHome/Zipcode/__snapshots__/Zipcode.test.js.snap
  client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
  client/src/User/UserRoutes.js
  client/src/User/__snapshots__/UserRoutes.test.js.snap
Labels: Feature/Enhancement

#85 Quick Zip Fix
  client/src/User/UserHome/Zipcode/Zipcode.js
Labels: bug

#86 Gerry test warning fix
  client/package.json
  client/src/Config.js
  client/src/User/UserHome/UserHome.js
  client/src/User/UserRoutes.test.js
  client/src/User/__snapshots__/UserRoutes.test.js.snap
  client/src/index.js
Labels: Test Cases

#90 Added firebase login mock test for user login
  client/src/Home/Home.test.js
  client/src/Home/__snapshots__/Home.test.js.snap
Labels: Test Cases

#87 Integrate googlemaps yelp
  client/src/BusinessCard/BusinessCard.css
  client/src/BusinessCard/BusinessCard.js
  client/src/BusinessCard/BusinessCard.test.js
  client/src/BusinessCard/ReviewList/Review.css
  client/src/BusinessCard/ReviewList/Review.js
  client/src/BusinessCard/ReviewList/Review.test.js
  client/src/BusinessCard/ReviewList/ReviewList.css
  client/src/BusinessCard/ReviewList/ReviewList.js
  client/src/BusinessCard/ReviewList/ReviewList.test.js
  client/src/BusinessCard/ReviewList/__snapshots__/Review.test.js.snap
  client/src/BusinessCard/ReviewList/__snapshots__/ReviewList.test.js.snap
  client/src/BusinessCard/__snapshots__/BusinessCard.test.js.snap
  client/src/BusinessCardList/BusinessCard.css
  client/src/BusinessCardList/BusinessCard.js
  client/src/BusinessCardList/BusinessCardList.css
  client/src/BusinessCardList/BusinessCardList.js
  client/src/BusinessCardList/BusinessCardList.test.js
  client/src/BusinessCardList/ReviewList/Review.css
  client/src/BusinessCardList/ReviewList/Review.js
  client/src/BusinessCardList/ReviewList/ReviewList.css
  client/src/BusinessCardList/ReviewList/ReviewList.js
  client/src/BusinessCardList/ReviewList/__snapshots__/Review.test.js.snap
  client/src/BusinessCardList/ReviewList/__snapshots__/ReviewList.test.js.snap
  client/src/BusinessCardList/__snapshots__/BusinessCard.test.js.snap
  client/src/BusinessCardList/__snapshots__/BusinessCardList.test.js.snap
  client/src/Map/__snapshots__/googleMaps.test.js.snap
  client/src/Map/googleMaps.js
  client/src/Map/googleMaps.test.js
  client/src/Map/map.css
  client/src/User/UserHome/UserHome.js
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.css
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
  client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
  client/src/User/UserHome/Zipcode/Zipcode.js
  client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
  package.json
Labels: Feature/Enhancement

#92 Fixed Places not loading bug
  client/src/Map/googleMaps.js
Labels: bug

#94 Gerry responsive ui & mobile signup/login text field input fixes
  client/src/Home/Home.css
  client/src/Home/Home.js
  client/src/Home/Signup/Signup.js
  client/src/Home/Signup/__snapshots__/Signup.test.js.snap
  client/src/Home/__snapshots__/Home.test.js.snap
  client/src/Map/googleMaps.js
  client/src/User/UserHome/UserHome.css
  client/src/User/UserHome/UserHome.js
  client/src/User/UserHome/UserProfile/UserProfile.js
  client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
  client/src/User/UserHome/Zipcode/Zipcode.css
  client/src/User/UserHome/Zipcode/Zipcode.js
  client/src/User/UserHome/Zipcode/__snapshots__/Zipcode.test.js.snap
  client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
  client/src/index.css
  client/src/index.js
Labels: Feature/Enhancement, bug

#93 Fixed the bug that causes the restaurants with same name to not render
  client/src/BusinessCard/BusinessCard.js
Labels: bug

#97 Bug fix that allows mobile devices to allow text input when viewing our website
  client/src/Home/Home.css
Labels: bug

#99 Gerry userprofile test
  client/src/User/UserHome/UserProfile/UserProfile.test.js
  client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
Labels: bug
