Repository CSC59939/LunchIn, pull requests merged in 2018-11, with the labels that each got.

#28 CHC Unit Tests for the Frontend
  .gitignore
  package.json
  src/User/UserHome/Review/Review.test.js
  src/User/UserHome/Review/__snapshots__/Review.test.js.snap
  src/User/UserHome/UserHome.test.js
  src/User/UserHome/UserProfile/UserProfile.test.js
  src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
  src/User/UserHome/__snapshots__/UserHome.test.js.snap
  src/User/UserRoutes.test.js
  src/User/__snapshots__/UserRoutes.test.js.snap
Labels: enhancement

#29 Added APIs to retreive api keys from the backend.
  package.json
  server/controllers/apiKeys.js
  server/routes/routes.js
  server/server.js
  server/test/apiKeys.test.js
Labels: enhancement

#41 Chc yelp api
  server.js
  server/controllers/yelpApi.js
  server/routes/routes.js
  server/server.js
  server/test/test.js
  server/test/yelpApi.test.js
  src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
Labels: enhancement

#58 Deploying to Heroku. Restructured the root directory.
  client/.firebaserc
  client/.gitignore
  client/database.rules.json
  client/firebase.json
  client/package.json
  client/public/404.html
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/App.test.js
  client/src/Config.js
  client/src/Home/Home.css
  client/src/Home/Home.js
  client/src/Home/Home.test.js
  client/src/Home/Signup/Signup.css
  client/src/Home/Signup/Signup.js
  client/src/Home/Signup/Signup.test.js
  client/src/Home/Signup/__snapshots__/Signup.test.js.snap
  client/src/Home/__snapshots__/Home.test.js.snap
  client/src/Images/Wallpaper.jpeg
  client/src/Map/__snapshots__/googleMaps.test.js.snap
  client/src/Map/googleMaps.js
  client/src/Map/googleMaps.test.js
  client/src/Map/map.css
  client/src/User/UserHome/Review/Review.css
  client/src/User/UserHome/Review/Review.js
  client/src/User/UserHome/Review/Review.test.js
  client/src/User/UserHome/Review/__snapshots__/Review.test.js.snap
  client/src/User/UserHome/UserHome.css
  client/src/User/UserHome/UserHome.js
  client/src/User/UserHome/UserHome.test.js
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.css
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.test.js
  client/src/User/UserHome/UserInputFoodChoices/__snapshots__/UserInputFoodChoices.test.js.snap
  client/src/User/UserHome/UserProfile/UserProfile.css
  client/src/User/UserHome/UserProfile/UserProfile.js
  client/src/User/UserHome/UserProfile/UserProfile.test.js
  client/src/User/UserHome/UserProfile/__snapshots__/UserProfile.test.js.snap
  client/src/User/UserHome/__snapshots__/UserHome.test.js.snap
  client/src/User/UserRoutes.js
  client/src/User/UserRoutes.test.js
  client/src/User/__snapshots__/UserRoutes.test.js.snap
  client/src/__snapshots__/App.test.js.snap
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/.gitignore
  server/controllers/yelpApi.js
  server/package.json
  server/routes/routes.js
  server/server.js
  server/test/test.js
  test/README.md
  test/mocha_tests.sh
Labels: Feature/Enhancement, important

#66 Luis gmapscss
  client/src/Map/__snapshots__/googleMaps.test.js.snap
  client/src/Map/googleMaps.js
  client/src/Map/map.css
  package-lock.json
Labels: Feature/Enhancement

#64 Chc reviews from yelp
  client/src/BusinessCardList/BusinessCard.css
  client/src/BusinessCardList/BusinessCard.js
  client/src/BusinessCardList/BusinessCard.test.js
  client/src/BusinessCardList/BusinessCardList.css
  client/src/BusinessCardList/BusinessCardList.js
  client/src/BusinessCardList/BusinessCardList.test.js
  client/src/BusinessCardList/ReviewList/Review.css
  client/src/BusinessCardList/ReviewList/Review.js
  client/src/BusinessCardList/ReviewList/Review.test.js
  client/src/BusinessCardList/ReviewList/ReviewList.css
  client/src/BusinessCardList/ReviewList/ReviewList.js
  client/src/BusinessCardList/ReviewList/ReviewList.test.js
  client/src/BusinessCardList/ReviewList/__snapshots__/Review.test.js.snap
  client/src/BusinessCardList/ReviewList/__snapshots__/ReviewList.test.js.snap
  client/src/BusinessCardList/__snapshots__/BusinessCard.test.js.snap
  client/src/BusinessCardList/__snapshots__/BusinessCardList.test.js.snap
  client/src/User/UserHome/Review/Review.js
  client/src/User/UserHome/Review/__snapshots__/Review.test.js.snap
  client/src/User/UserHome/UserInputFoodChoices/UserInputFoodChoices.js
Labels: Feature/Enhancement

#80 Gerry router test
  client/src/App.test.js
  client/src/__snapshots__/App.test.js.snap
Labels: Test Cases
